openapi: 3.0.3
info:
  title: University Professor Service API
  version: 1.0.0
  description: API для управління даними професорів університету за допомогою Servlet API та Statement.

servers:
  - url: http://localhost:8080
    description: Локальний сервер Tomcat

paths:
  /professors:
    get:
      summary: Отримати список професорів або виконати пошук /professor/{id}
      description: |
        Повертає список професорів. Якщо параметри відсутні — повертає повний список.

      responses:
        '200':
          description: Успішне отримання списку професорів
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/OutpouProfessorDto'
        '500':
          description: Внутрішня помилка сервера або бази даних
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

    post:
      summary: Створити нового професора
      description: |
        Приймає параметри нового професора, виконує валідацію на кількість параметрів (має бути рівно 3)
        та додає запис до бази даних через Statement.executeUpdate().
      parameters:
        - name: name
          in: query
          required: true
          description: Повне ім'я нового професора
          schema:
            type: string
          example: Isac Molibden
        - name: email
          in: query
          required: true
          description: Електронна адреса нового професора
          schema:
            type: string
          example: im@oxford.edu
        - name: department_id
          in: query
          required: true
          description: Ідентифікатор кафедри/департаменту
          schema:
            type: integer
          example: 5
      responses:
        '201':
          description: Професора успішно створено
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Professor'
        '400':
          description: Помилка валідації (невірна кількість або формат параметрів)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Внутрішня помилка сервера або помилка виконання SQL-інсерту
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    put:
        summary: Оновити існуючого професора
        description: |
          Приймає параметри, як для нового професора, виконує валідацію на кількість параметрів (має бути рівно 4)
          та додає запис до бази даних через Statement.executeUpdate().
        parameters:
          -  name: id
             in: query
             required: true
             description: id існуючого професора
             schema:
               type: integer
             example: 20

          - name: name
            in: query
            required: true
            description: Повне ім'я нового професора
            schema:
              type: string
            example: Isac Molibden
          - name: email
            in: query
            required: true
            description: Електронна адреса нового професора
            schema:
              type: string
            example: im@oxford.edu
          - name: department_id
            in: query
            required: true
            description: Ідентифікатор кафедри/департаменту
            schema:
              type: integer
            example: 5
        responses:
          '200':
            description: Професора успішно оновлено
            content:
              application/json:
                schema:
                  type: array
                  items:
                    $ref: '#/components/schemas/Professor'
          '400':
            description: Помилка валідації (невірна кількість або формат параметрів)
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/ErrorResponse'
          '500':
            description: Внутрішня помилка сервера або помилка виконання SQL-інсерту
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/ErrorResponse'
    delete:
      summary: Видалити професора
      description: |
        Видаляє професора по id .
      parameters:
        - name: id
          in: query
          required: true
          description: Id професора
          schema:
            type: integer
          example: 31

      responses:
        '202':
          description: Професора видалено
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Professor'
        '400':
          description: Помилка валідації (невірна кількість або формат параметрів)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Внутрішня помилка сервера або помилка виконання SQL-інсерту
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /students:
    get:
      tags:
        - Students
      summary: Get all students
      operationId: getAllStudents
      responses:
        '200':
          description: List of students
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ResponseStudentDto'

    post:
      tags:
        - Students
      summary: Create new student
      operationId: createStudent
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RequestStudentDto'
      responses:
        '201':
          description: Student created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseStudentDto'

        '400':
          description: Invalid request

  /students/{id}:
      get:
        tags:
          - Students
        summary: Get student by id
        operationId: getStudentById
        parameters:
          - name: id
            in: path
            required: true
            schema:
              type: integer
        responses:
          '200':
            description: Student found
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/ResponseStudentDto'

          '404':
            description: Student not found

      put:
        tags:
          - Students
        summary: Update student
        operationId: updateStudent
        parameters:
          - name: id
            in: path
            required: true
            schema:
              type: integer

        requestBody:
          required: true
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RequestStudentDto'

        responses:
          '200':
            description: Student updated
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/ResponseStudentDto'

          '404':
            description: Student not found

      delete:
        tags:
          - Students
        summary: Delete student
        operationId: deleteStudent
        parameters:
          - name: id
            in: path
            required: true
            schema:
              type: integer

        responses:
          '204':
            description: Student deleted

          '404':
            description: Student not found

components:
  schemas:
    OutpouProfessorDto:
      type: object
      properties:
        id:
          type: string
          example: Diana Bishop
        name:
          type: string
          example: Diana Bishop
        email:
          type: string
          example: db@oxford.edu
        departmentId:
            type: integer
            example: 5
      required:
        - id


    Professor:
      type: object
      properties:
        id:
          type: integer
          example: 0
        name:
          type: string
          example: Isac Molibden
        email:
          type: string
          example: im@osford.edu
        department:
          type: integer
          example: Law
        departmentId:
          type: integer
          example: 5
      required:
        - id
        - name
        - email
        - departmentId

    ErrorResponse:
      type: object
      properties:
        error:
          type: string
          example: Invalid parameters count or format. Expected name,email,department_id
    RequestStudentDto:
      type: object
      required:
        - name
        - email
        - enrollmentDate
        - birthday
        - fundingSource
        - admissionScore
        - specialNeeds
        - address
        - phoneNumber

      properties:

        name:
          type: string
          example: Arnold Arnold

        email:
          type: string
          example: aa@student.edu

        enrollmentDate:
          type: string
          format: date
          example: 2026-01-01

        birthday:
          type: string
          format: date
          example: 2010-01-01

        fundingSource:
          type: string
          example: credit

        admissionScore:
          type: integer
          example: 5

        specialNeeds:
          type: boolean
          example: false

        address:
          type: string
          example: A City, B Str

        phoneNumber:
          type: string
          example: "0502589750"

    ResponseStudentDto:
      type: object

      properties:

        id:
          type: integer
          example: 12

        name:
          type: string
          example: Arnold Arnold

        email:
          type: string
          example: aa@student.edu

        enrollmentDate:
          type: string
          format: date
          example: 2026-01-01

        birthday:
          type: string
          format: date
          example: 2010-01-01

        fundingSource:
          type: string
          example: credit

        admissionScore:
          type: integer
          example: 5

        specialNeeds:
          type: boolean
          example: false

        address:
          type: string
          example: A City, B Str

        phoneNumber:
          type: string
          example: "0502589750"