openapi: 3.0.3
info:
  title: University Professor Service API
  version: 1.0.0
  description: API для управління даними професорів університету за допомогою Servlet API та Statement.

servers:
  - url: http://localhost:8080
    description: Локальний сервер Tomcat

paths:
  /professors:
    get:
      tags:
        - Professors
      summary: Отримати список професорів або виконати пошук /professor/{id}
      description: |
        Повертає список професорів. Якщо параметри відсутні — повертає повний список.

      responses:
        '200':
          description: Успішне отримання списку професорів
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ResponseProfessorDto'
        '500':
          description: Внутрішня помилка сервера або бази даних
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

    post:
      tags:
        - Professors
      summary: Створити нового професора
      description: |
        Приймає параметри нового професора, виконує валідацію на кількість параметрів (має бути рівно 3)
        та додає запис до бази даних через Statement.executeUpdate().
      parameters:
        - name: name
          in: query
          required: true
          description: Повне ім'я нового професора
          schema:
            type: string
          example: Isac Molibden
        - name: email
          in: query
          required: true
          description: Електронна адреса нового професора
          schema:
            type: string
          example: im@oxford.edu
        - name: department_id
          in: query
          required: true
          description: Ідентифікатор кафедри/департаменту
          schema:
            type: integer
          example: 5
      responses:
        '201':
          description: Професора успішно створено
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Professor'
        '400':
          description: Помилка валідації (невірна кількість або формат параметрів)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Внутрішня помилка сервера або помилка виконання SQL-інсерту
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    put:
      tags:
        - Professors
      summary: Оновити існуючого професора
      description:
        Приймає параметри, як для нового професора, виконує валідацію на кількість параметрів (має бути рівно 4)
        та додає запис до бази даних через Statement.executeUpdate().
      parameters:
        - name: id
          in: query
          required: true
          description: id існуючого професора
          schema:
            type: integer
          example: 20

        - name: name
          in: query
          required: true
          description: Повне ім'я нового професора
          schema:
            type: string
          example: Isac Molibden
        - name: email
          in: query
          required: true
          description: Електронна адреса нового професора
          schema:
            type: string
          example: im@oxford.edu
        - name: department_id
          in: query
          required: true
          description: Ідентифікатор кафедри/департаменту
          schema:
            type: integer
          example: 5
      responses:
        '200':
          description: Професора успішно оновлено
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Professor'
        '400':
          description: Помилка валідації (невірна кількість або формат параметрів)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Внутрішня помилка сервера або помилка виконання SQL-інсерту
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    delete:
      tags:
        - Professors
      summary: Видалити професора
      description: |
        Видаляє професора по id .
      parameters:
        - name: id
          in: query
          required: true
          description: Id професора
          schema:
            type: integer
          example: 31

      responses:
        '202':
          description: Професора видалено
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Professor'
        '400':
          description: Помилка валідації (невірна кількість або формат параметрів)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Внутрішня помилка сервера або помилка виконання SQL-інсерту
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /students:
    get:
      tags:
        - Students
      summary: Get all students
      operationId: getAllStudents
      responses:
        '200':
          description: List of students
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ResponseStudentDto'

    post:
      tags:
        - Students
      summary: Create new student
      operationId: createStudent
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RequestStudentDto'
      responses:
        '201':
          description: Student created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseStudentDto'

        '400':
          description: Invalid request

  /students/{id}:
    get:
      tags:
        - Students
      summary: Get student by id
      operationId: getStudentById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Student found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseStudentDto'

        '404':
          description: Student not found

    put:
      tags:
        - Students
      summary: Update student
      operationId: updateStudent
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer

      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RequestStudentDto'

      responses:
        '200':
          description: Student updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseStudentDto'

        '404':
          description: Student not found

    delete:
      tags:
        - Students
      summary: Delete student
      operationId: deleteStudent
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer

      responses:
        '204':
          description: Student deleted

        '404':
          description: Student not found

  /courses:
    get:
      tags:
        - Courses
      summary: Get all courses
      operationId: getAllCourses
      responses:
        '200':
          description: List of courses
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ResponseCourseDto'

    post:
      tags:
        - Courses
      summary: Create new course
      operationId: createCourse
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RequestCourseDto'
      responses:
        '201':
          description: Course created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseCourseDto'

        '400':
          description: Invalid request

  /courses/{id}:
    get:
      tags:
        - Courses
      summary: Get course by id
      operationId: getCourseById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Course found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseCourseDto'

        '404':
          description: Course not found

    put:
      tags:
        - Courses
      summary: Update course
      operationId: updateCourse
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer

      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RequestCourseDto'

      responses:
        '200':
          description: Course updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseCourseDto'

        '404':
          description: Course not found

    delete:
      tags:
        - Courses
      summary: Delete course
      operationId: deleteCourse
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer

      responses:
        '204':
          description: Course deleted

        '404':
          description: Course not found

  /offerings:
    get:
      tags:
        - Offerings
      summary: Get all offerings
      operationId: getAllOfferings
      responses:
        '200':
          description: List of oferings
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ResponseOfferingDto'

    post:
      tags:
        - Offerings
      summary: Create new offering
      operationId: createOffering
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RequestOfferingDto'
      responses:
        '201':
          description: Course offering
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseOfferingDto'

        '400':
          description: Invalid request

  /offerings/{id}:
    get:
      tags:
        - Offerings
      summary: Get offering by id
      operationId: getOfferingById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Offering found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseOfferingDto'

        '404':
          description: Offering not found

    put:
      tags:
        - Offerings
      summary: Update offering
      operationId: updateOffering
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer

      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RequestOfferingDto'

      responses:
        '200':
          description: Offering updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseOfferingDto'

        '404':
          description: Offering not found

    delete:
      tags:
        - Offerings
      summary: Delete offering
      operationId: deleteOffering
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer

      responses:
        '204':
          description: Offering deleted

        '404':
          description: Offering not found

components:
  schemas:
    ResponseProfessorDto:
      type: object
      properties:
        id:
          type: string
          example: Diana Bishop
        name:
          type: string
          example: Diana Bishop
        email:
          type: string
          example: db@oxford.edu
        departmentId:
          type: integer
          example: 5
      required:
        - id

    Professor:
      type: object
      properties:
        id:
          type: integer
          example: 0
        name:
          type: string
          example: Isac Molibden
        email:
          type: string
          example: im@osford.edu
        department:
          type: integer
          example: Law
        departmentId:
          type: integer
          example: 5
      required:
        - id
        - name
        - email
        - departmentId

    ErrorResponse:
      type: object
      properties:
        error:
          type: string
          example: Invalid parameters count or format. Expected name,email,department_id

    RequestStudentDto:
      type: object
      required:
        - name
        - email
        - enrollmentDate
        - birthday
        - fundingSource
        - admissionScore
        - specialNeeds
        - address
        - phoneNumber

      properties:
        name:
          type: string
          example: Arnold Arnold
        email:
          type: string
          example: aa@student.edu
        enrollmentDate:
          type: string
          format: date
          example: 2026-01-01
        birthday:
          type: string
          format: date
          example: 2010-01-01
        fundingSource:
          type: string
          example: credit
        admissionScore:
          type: integer
          example: 5
        specialNeeds:
          type: boolean
          example: false
        address:
          type: string
          example: A City, B Str
        phoneNumber:
          type: string
          example: "0502589750"

    ResponseStudentDto:
      type: object

      properties:
        id:
          type: integer
          example: 12
        name:
          type: string
          example: Arnold Arnold
        email:
          type: string
          example: aa@student.edu
        enrollmentDate:
          type: string
          format: date
          example: 2026-01-01
        birthday:
          type: string
          format: date
          example: 2010-01-01
        fundingSource:
          type: string
          example: credit
        admissionScore:
          type: integer
          example: 5
        specialNeeds:
          type: boolean
          example: false
        address:
          type: string
          example: A City, B Str
        phoneNumber:
          type: string
          example: "0502589750"

    RequestCourseDto:
      type: object
      required:
        - courseCode
        - title
        - numberOfCredits
        - departmentId
        - courseCategory

      properties:
        courseCode:
          type: string
          example: 01-45
        title:
          type: string
          example: L_04
        numberOfCresits:
          type: integer
          example: 3
        departmentId:
          type: integer
          example: 5
        courseCategory:
          type: string
          example: STEM

    ResponseCourseDto:
      type: object

      properties:
        id:
          type: integer
          example: 1
        courseCode:
          type: string
          example: L_01
        title:
          type: string
          example: Law_advance
        numberOfCredits:
          type: integer
          example: 1
        departmentId:
          type: integer
          example: 5
        department:
          type: string
          example: Law

    RequestOfferingDto:
      type: object
      required:
        - courseId
        - termId
        - professorId

      properties:
        courseId:
          type: integer
          example: 1
        termId:
          type: integer
          example: 20
        professorId:
          type: integer
          example: 3

    ResponseOfferingDto:
      type: object

      properties:
        id:
          type: integer
          example: 1
        courseId:
          type: in'
          example: 1
        termId:
          type: integer
          example: 13
        professorId:
          type: integer
          example: 1
